// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SapReplitAPI.Migrations
{
    [DbContext(typeof(CacheDbContext))]
    [Migration("20250724092100_InitCacheSchema")]
    partial class InitCacheSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("CachedProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OnHand")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OnHandQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("U_Article_No")
                        .HasColumnType("TEXT");

                    b.Property<string>("U_Item_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("U_MdlTEST")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedInvoice", b =>
                {
                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BalanceDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysOverdue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DocTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PaidToDate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalesEmployeeCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SalesEmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DocEntry");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedInvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dscription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LineNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("U_Item_Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("U_MDLTsT")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedInvoicePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BankTransferAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankTransferReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DebitAccountCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DebitAccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SalesEmployeeCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalesEmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InvoicePayments");
                });

            modelBuilder.Entity("SyncMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("SyncMetadata");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedInvoiceLine", b =>
                {
                    b.HasOne("SapReplitAPI.Models.Cache.CachedInvoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedInvoice", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
