// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SapReplitAPI.Migrations
{
    [DbContext(typeof(CacheDbContext))]
    [Migration("20260829000001_AddDeliveryCache")]
    partial class AddDeliveryCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");
#pragma warning restore 612, 618
        }
    }
}
