// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SapReplitAPI.Migrations
{
    [DbContext(typeof(CacheDbContext))]
    [Migration("20260927212231_AddNeonMirrorWork")]
    partial class AddNeonMirrorWork
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("CachedItemPriceList", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceListNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ItemCode", "PriceListNum");

                    b.ToTable("ItemPriceLists");
                });

            modelBuilder.Entity("CachedPriceList", b =>
                {
                    b.Property<int>("PriceListNum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BasePriceList")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Factor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValue(1m);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceListName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PriceListNum");

                    b.ToTable("PriceLists");
                });

            modelBuilder.Entity("CachedProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OnHand")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OnHandQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price01")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price02")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price04")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price05")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalOnHand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("U_Article_No")
                        .HasColumnType("TEXT");

                    b.Property<string>("U_Item_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("U_MdlTEST")
                        .HasColumnType("TEXT");

                    b.Property<string>("U_OE_Numbers")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Whs_001")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0);

                    b.Property<int?>("Whs_002")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0);

                    b.Property<int?>("Whs_003")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0);

                    b.Property<int?>("Whs_004")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TwoFASecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedCreditMemo", b =>
                {
                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Canceled")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DocTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("U_AppRef")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("DocEntry");

                    b.HasIndex("CardCode")
                        .HasDatabaseName("IX_CreditMemoHeaders_CardCode");

                    b.HasIndex("DocDate")
                        .HasDatabaseName("IX_CreditMemoHeaders_DocDate");

                    b.ToTable("CreditMemoHeaders", (string)null);
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedCreditMemoLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseLine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dscription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int?>("InvoiceDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvoiceLineNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LineNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry")
                        .HasDatabaseName("IX_CreditMemoLines_DocEntry");

                    b.HasIndex("DocEntry", "LineNum")
                        .IsUnique()
                        .HasDatabaseName("UX_CreditMemoLines_DocEntry_LineNum");

                    b.ToTable("CreditMemoLines", (string)null);
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedDelivery", b =>
                {
                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BPLId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Canceled")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateTS")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocCur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocStatusDisplay")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<decimal>("DocTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<DateTime>("TaxDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("U_ReplitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateTS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserSign")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZoneRef")
                        .HasColumnType("TEXT");

                    b.HasKey("DocEntry");

                    b.HasIndex("CardCode");

                    b.HasIndex("DocDate");

                    b.HasIndex("DocNum");

                    b.HasIndex("DocStatus", "Canceled");

                    b.ToTable("Deliveries", (string)null);
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedDeliveryLine", b =>
                {
                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseLine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Dscription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpenQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrgetEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DocEntry", "LineNum");

                    b.HasIndex("DocEntry")
                        .HasDatabaseName("IX_DeliveryLines_DocEntry");

                    b.HasIndex("ItemCode")
                        .HasDatabaseName("IX_DeliveryLines_ItemCode");

                    b.ToTable("DeliveryLines", (string)null);
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedInvoice", b =>
                {
                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BalanceDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Canceled")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysOverdue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("DeliveryLocation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocStatusDisplay")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<decimal>("DocTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GroupNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("InvoiceDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PaidToDate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalesEmployeeCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SalesEmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("U_ReplitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneRef")
                        .HasColumnType("TEXT");

                    b.HasKey("DocEntry");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedInvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseLine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dscription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LineNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PendingReturnQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReturnedQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("U_ItemName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("U_Item_Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("U_MDLTsT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("U_Manufacturer")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("U_MdlTEST")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedInvoicePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BankTransferAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankTransferReference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<bool>("Canceled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("CounterRef")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("DebitAccountCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("DebitAccountName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SalesEmployeeCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("SalesEmployeeName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.HasIndex("PaymentDocEntry");

                    b.HasIndex("DocEntry", "PaymentDocEntry")
                        .IsUnique();

                    b.ToTable("InvoicePayments");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedOpenOrder", b =>
                {
                    b.Property<int>("DocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DocEntry");

                    b.ToTable("OpenOrderHeaders");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedOpenOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dscription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LineNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.ToTable("OpenOrderLines");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedOrder", b =>
                {
                    b.Property<int>("DocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OrderValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DocEntry");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dscription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LineNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("U_ItemName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("U_Manufacturer")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry", "LineNum")
                        .IsUnique();

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedPickList", b =>
                {
                    b.Property<int>("AbsEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Canceled")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("N");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryLocation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("OwnerCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<DateTime>("PickDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int?>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("U_ReplitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneRef")
                        .HasColumnType("TEXT");

                    b.HasKey("AbsEntry");

                    b.HasIndex("OwnerCode")
                        .HasDatabaseName("IX_PickLists_OwnerCode");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PickLists_Status");

                    b.HasIndex("UpdateDate")
                        .HasDatabaseName("IX_PickLists_UpdateDate");

                    b.ToTable("PickLists", (string)null);
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedPickListBinAllocation", b =>
                {
                    b.Property<int>("AbsEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PickEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pkl2LinNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BinAbsEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BinCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("DeliveryLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<decimal>("OpenCreQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("OrderEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PickListName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("PickListStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<decimal>("PickQtty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RelQtty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("U_ReplitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ZoneRef")
                        .HasColumnType("TEXT");

                    b.HasKey("AbsEntry", "PickEntry", "Pkl2LinNum");

                    b.HasIndex("AbsEntry")
                        .HasDatabaseName("IX_PickListBinAllocations_AbsEntry");

                    b.HasIndex("BinAbsEntry")
                        .HasDatabaseName("IX_PickListBinAllocations_BinAbsEntry");

                    b.ToTable("PickListBinAllocations", (string)null);
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedPickListLine", b =>
                {
                    b.Property<int>("AbsEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PickEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseObject")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dscription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("OrderEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderLine")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PickQtty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PickStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("PickedTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrevReleas")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RelQtty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SourceSoDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("U_ReplitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ZoneRef")
                        .HasColumnType("TEXT");

                    b.HasKey("AbsEntry", "PickEntry");

                    b.HasIndex("AbsEntry")
                        .HasDatabaseName("IX_PickListLines_AbsEntry");

                    b.HasIndex("OrderEntry")
                        .HasDatabaseName("IX_PickListLines_OrderEntry");

                    b.ToTable("PickListLines", (string)null);
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedReturnRequest", b =>
                {
                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Canceled")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DocTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("U_AppRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("U_ReplitId")
                        .HasColumnType("TEXT");

                    b.HasKey("DocEntry");

                    b.HasIndex("CardCode")
                        .HasDatabaseName("IX_ReturnRequests_CardCode");

                    b.HasIndex("DocDate")
                        .HasDatabaseName("IX_ReturnRequests_DocDate");

                    b.ToTable("ReturnRequests", (string)null);
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedReturnRequestLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseLine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dscription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LineNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<decimal>("OpenQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry")
                        .HasDatabaseName("IX_ReturnRequestLines_DocEntry");

                    b.HasIndex("DocEntry", "LineNum")
                        .IsUnique()
                        .HasDatabaseName("UX_ReturnRequestLines_DocEntry_LineNum");

                    b.HasIndex("BaseType", "BaseEntry", "BaseLine")
                        .HasDatabaseName("IX_ReturnRequestLines_BaseRef");

                    b.ToTable("ReturnRequestLines", (string)null);
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedTodayOrder", b =>
                {
                    b.Property<int>("DocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OrderValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DocEntry");

                    b.ToTable("TodayOrderHeaders");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedTodayOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dscription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("U_ItemName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("U_Manufacturer")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.ToTable("TodayOrderLines");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedZoneFulfillmentReport", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliveryDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryLocation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InvoiceDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvoiceDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .HasColumnType("TEXT");

                    b.Property<long>("OrchestrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalesOrderDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalesOrderDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotSha256")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("U_ReplitId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneRef")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("ReportId");

                    b.HasIndex("DeliveryDocEntry")
                        .HasDatabaseName("IX_ZfReports_DeliveryDocEntry");

                    b.HasIndex("InvoiceDocEntry")
                        .HasDatabaseName("IX_ZfReports_InvoiceDocEntry");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("IX_ZfReports_RequestId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ZfReports_Status");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("IX_ZfReports_UpdatedAtUtc");

                    b.ToTable("ZoneFulfillmentReports", (string)null);
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedZoneFulfillmentReportLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BinAbsEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BinCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BinQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("DeliveredQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("DeliveryLineNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InvoiceBaseEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvoiceBaseLine")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvoiceBaseType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvoiceLineNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LineSeq")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OpklAbsEntry")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PickedQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PickerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PickerUserCode")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PickerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RequestedQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SalesOrderBaseLine")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WhsCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("IX_ZfReportLines_ReportId");

                    b.HasIndex("ReportId", "LineSeq")
                        .IsUnique()
                        .HasDatabaseName("UX_ZfReportLines_ReportId_LineSeq");

                    b.ToTable("ZoneFulfillmentReportLines", (string)null);
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.DetailedInvoiceStatusCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CashSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CreditSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentsStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PostingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReinvoicedFrom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReturnedCashInvoice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SalesName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DetailedInvoiceStatusCache");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.PaymentIdempotencyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentDocNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientReference")
                        .IsUnique();

                    b.ToTable("PaymentIdempotencyLogs", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.SalesTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SalesEmployeeCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SalesEmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SalesTargets");
                });

            modelBuilder.Entity("SapReplitAPI.Models.CachedProducts.CachedCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Region")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int?>("SalesPersonCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SalesPersonName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VIN1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("VIN2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("VIN3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("CardCode")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SapReplitAPI.Models.GlAccountStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("InvoiceDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvoiceDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineMemo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int?>("PaymentDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaymentDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ref1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Ref2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<DateTime>("RefDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("TransId", "Account")
                        .IsUnique();

                    b.ToTable("AccountStatements", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SapReplitAPI.Models.Inventory.BinInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BinAbsEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BinCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BinOnHand")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .HasDatabaseName("IX_BinInventory_ItemCode");

                    b.HasIndex("LastUpdated")
                        .HasDatabaseName("IX_BinInventory_LastUpdated");

                    b.HasIndex("WhsCode")
                        .HasDatabaseName("IX_BinInventory_WhsCode");

                    b.HasIndex("ItemCode", "WhsCode")
                        .HasDatabaseName("IX_BinInventory_ItemCode_WhsCode");

                    b.HasIndex("ItemCode", "WhsCode", "BinAbsEntry")
                        .IsUnique()
                        .HasDatabaseName("UX_BinInventory_ItemCode_WhsCode_BinAbsEntry");

                    b.ToTable("BinInventory", (string)null);
                });

            modelBuilder.Entity("SapReplitAPI.Models.Inventory.WarehouseInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvailableToSell")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsBinManaged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("IsCommitted")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OnHand")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OnOrder")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .HasDatabaseName("IX_WarehouseInventory_ItemCode");

                    b.HasIndex("LastUpdated")
                        .HasDatabaseName("IX_WarehouseInventory_LastUpdated");

                    b.HasIndex("WhsCode")
                        .HasDatabaseName("IX_WarehouseInventory_WhsCode");

                    b.HasIndex("ItemCode", "WhsCode")
                        .IsUnique()
                        .HasDatabaseName("UX_WarehouseInventory_ItemCode_WhsCode");

                    b.ToTable("WarehouseInventory", (string)null);
                });

            modelBuilder.Entity("SapReplitAPI.Models.Invoicing.InvoiceFromDeliveryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliveryDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InvoiceDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvoiceDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryDocEntry", "Status");

                    b.ToTable("InvoiceFromDeliveryLogs", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SapReplitAPI.Models.NeonMirror.NeonMirrorWork", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceEventId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityKey");

                    b.HasIndex("Status", "Priority", "CreatedAtUtc");

                    b.ToTable("NeonMirrorWork");
                });

            modelBuilder.Entity("SapReplitAPI.Models.SoDelivery.SoDeliveryLineLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BinAllocationsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("LineNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("OnHandAfter")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OnHandBefore")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OpenQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("LogId")
                        .HasDatabaseName("IX_SoDeliveryLineLogs_LogId");

                    b.ToTable("SoDeliveryLineLogs", (string)null);
                });

            modelBuilder.Entity("SapReplitAPI.Models.SoDelivery.SoDeliveryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int?>("DeliveryDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeliveryDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SapErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SapErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("IX_SoDeliveryLogs_RunId");

                    b.HasIndex("SoDocEntry")
                        .HasDatabaseName("IX_SoDeliveryLogs_SoDocEntry");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SoDeliveryLogs_Status");

                    b.HasIndex("RunId", "SoDocEntry")
                        .IsUnique()
                        .HasDatabaseName("UX_SoDeliveryLogs_RunId_SoDocEntry");

                    b.ToTable("SoDeliveryLogs", (string)null);
                });

            modelBuilder.Entity("SapReplitAPI.Models.SoDelivery.SoDeliveryRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExceptionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("FailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsForced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("PdfPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Running");

                    b.Property<int>("SuccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalDeliveriesCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalOrders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Job");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingDate")
                        .HasDatabaseName("IX_SoDeliveryRuns_ProcessingDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SoDeliveryRuns_Status");

                    b.ToTable("SoDeliveryRuns", (string)null);
                });

            modelBuilder.Entity("SyncMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("SyncMetadata");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedInvoiceLine", b =>
                {
                    b.HasOne("SapReplitAPI.Models.Cache.CachedInvoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedOpenOrderLine", b =>
                {
                    b.HasOne("SapReplitAPI.Models.Cache.CachedOpenOrder", "Header")
                        .WithMany("Lines")
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Header");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedOrderLine", b =>
                {
                    b.HasOne("SapReplitAPI.Models.Cache.CachedOrder", null)
                        .WithMany()
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedTodayOrderLine", b =>
                {
                    b.HasOne("SapReplitAPI.Models.Cache.CachedTodayOrder", "Header")
                        .WithMany("Lines")
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Header");
                });

            modelBuilder.Entity("SapReplitAPI.Models.SoDelivery.SoDeliveryLineLog", b =>
                {
                    b.HasOne("SapReplitAPI.Models.SoDelivery.SoDeliveryLog", "Log")
                        .WithMany("Lines")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Log");
                });

            modelBuilder.Entity("SapReplitAPI.Models.SoDelivery.SoDeliveryLog", b =>
                {
                    b.HasOne("SapReplitAPI.Models.SoDelivery.SoDeliveryRun", "Run")
                        .WithMany("Logs")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedOpenOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedTodayOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SapReplitAPI.Models.SoDelivery.SoDeliveryLog", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SapReplitAPI.Models.SoDelivery.SoDeliveryRun", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
