// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SapReplitAPI.Migrations
{
    [DbContext(typeof(CacheDbContext))]
    [Migration("20260818000000_AddBinAllocationsToLineLog")]
    partial class AddBinAllocationsToLineLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            // ── Existing entities (unchanged) ─────────────────────────────────

            modelBuilder.Entity("CachedProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OnHand")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OnHandQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price05")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalOnHand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("U_Article_No")
                        .HasColumnType("TEXT");

                    b.Property<string>("U_Item_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("U_MdlTEST")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Whs_001")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0);

                    b.Property<int?>("Whs_002")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0);

                    b.Property<int?>("Whs_003")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0);

                    b.Property<int?>("Whs_004")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TwoFASecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedInvoice", b =>
                {
                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BalanceDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Canceled")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysOverdue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocStatusDisplay")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<decimal>("DocTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GroupNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("InvoiceDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PaidToDate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalesEmployeeCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SalesEmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DocEntry");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedInvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dscription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LineNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("U_ItemName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("U_Item_Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("U_MDLTsT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("U_Manufacturer")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("U_MdlTEST")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedInvoicePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BankTransferAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankTransferReference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DebitAccountCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("DebitAccountName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SalesEmployeeCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("SalesEmployeeName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.HasIndex("PaymentDocEntry");

                    b.HasIndex("DocEntry", "PaymentDocEntry")
                        .IsUnique();

                    b.ToTable("InvoicePayments");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedOpenOrder", b =>
                {
                    b.Property<int>("DocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DocEntry");

                    b.ToTable("OpenOrderHeaders");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedOpenOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dscription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LineNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.ToTable("OpenOrderLines");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedOrder", b =>
                {
                    b.Property<int>("DocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OrderValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DocEntry");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dscription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LineNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("U_ItemName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("U_Manufacturer")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry", "LineNum")
                        .IsUnique();

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedTodayOrder", b =>
                {
                    b.Property<int>("DocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocNum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OrderValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DocEntry");

                    b.ToTable("TodayOrderHeaders");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedTodayOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dscription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("U_ItemName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("U_Manufacturer")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.ToTable("TodayOrderLines");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.DetailedInvoiceStatusCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CashSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CreditSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentsStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PostingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReinvoicedFrom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReturnedCashInvoice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SalesName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DetailedInvoiceStatusCache");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.SalesTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SalesEmployeeCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SalesEmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SlpCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlpName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SalesTargets");
                });

            modelBuilder.Entity("SapReplitAPI.Models.CachedProducts.CachedCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Region")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<int?>("SalesPersonCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SalesPersonName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VIN1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("VIN2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("VIN3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("CardCode")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SyncMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("SyncMetadata");
                });

            // ── New entities: SO → Delivery audit tables ──────────────────────

            modelBuilder.Entity("SapReplitAPI.Models.SoDelivery.SoDeliveryRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProcessingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Running");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Job");

                    b.Property<bool>("IsForced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("TotalOrders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("SuccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("FailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("SkippedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ExceptionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalDeliveriesCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("PdfPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingDate")
                        .HasDatabaseName("IX_SoDeliveryRuns_ProcessingDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SoDeliveryRuns_Status");

                    b.ToTable("SoDeliveryRuns");
                });

            modelBuilder.Entity("SapReplitAPI.Models.SoDelivery.SoDeliveryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeliveryDocEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeliveryDocNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("SapErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SapErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("IX_SoDeliveryLogs_RunId");

                    b.HasIndex("SoDocEntry")
                        .HasDatabaseName("IX_SoDeliveryLogs_SoDocEntry");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SoDeliveryLogs_Status");

                    b.HasIndex("RunId", "SoDocEntry")
                        .IsUnique()
                        .HasDatabaseName("UX_SoDeliveryLogs_RunId_SoDocEntry");

                    b.ToTable("SoDeliveryLogs");
                });

            modelBuilder.Entity("SapReplitAPI.Models.SoDelivery.SoDeliveryLineLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OpenQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<decimal>("OnHandBefore")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("OnHandAfter")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("BinAllocationsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogId")
                        .HasDatabaseName("IX_SoDeliveryLineLogs_LogId");

                    b.ToTable("SoDeliveryLineLogs");
                });

            // ── Existing relationships (unchanged) ────────────────────────────

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedInvoiceLine", b =>
                {
                    b.HasOne("SapReplitAPI.Models.Cache.CachedInvoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedOpenOrderLine", b =>
                {
                    b.HasOne("SapReplitAPI.Models.Cache.CachedOpenOrder", "Header")
                        .WithMany("Lines")
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Header");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedOrderLine", b =>
                {
                    b.HasOne("SapReplitAPI.Models.Cache.CachedOrder", null)
                        .WithMany()
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedTodayOrderLine", b =>
                {
                    b.HasOne("SapReplitAPI.Models.Cache.CachedTodayOrder", "Header")
                        .WithMany("Lines")
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Header");
                });

            // ── New relationships: SO Delivery audit ──────────────────────────

            modelBuilder.Entity("SapReplitAPI.Models.SoDelivery.SoDeliveryLog", b =>
                {
                    b.HasOne("SapReplitAPI.Models.SoDelivery.SoDeliveryRun", "Run")
                        .WithMany("Logs")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SapReplitAPI.Models.SoDelivery.SoDeliveryLineLog", b =>
                {
                    b.HasOne("SapReplitAPI.Models.SoDelivery.SoDeliveryLog", "Log")
                        .WithMany("Lines")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Log");
                });

            // ── Existing navigations (unchanged) ──────────────────────────────

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedOpenOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SapReplitAPI.Models.Cache.CachedTodayOrder", b =>
                {
                    b.Navigation("Lines");
                });

            // ── New navigations: SO Delivery audit ────────────────────────────

            modelBuilder.Entity("SapReplitAPI.Models.SoDelivery.SoDeliveryRun", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("SapReplitAPI.Models.SoDelivery.SoDeliveryLog", b =>
                {
                    b.Navigation("Lines");
                });

#pragma warning restore 612, 618
        }
    }
}
